export interface Location {
  x: number
  y: number
}

// Phase 1: Mesh System
export interface TacticalNode {
  id: string; // e.g. "region-1-node-45"
  x: number;
  y: number;
  neighbors: string[]; // IDs of connected nodes
  terrain: 'plains' | 'forest' | 'urban' | 'water' | 'mountain';
  isBorder: boolean;
  regionId: string; // Which region generated this node?
}

// The mesh for the entire map
export interface TacticalMesh {
  nodes: TacticalNode[];
  edges: [TacticalNode, TacticalNode][]; // For rendering lines
}

export type AnchorType = 'centroid' | 'border' | 'sector' | 'feature';
// Base position tags - can be extended with any string for tactical state descriptions
export type PositionTag = 
  | 'center' 
  | 'front_line' 
  | 'rear_guard' 
  | 'rear' 
  | 'flank_left' 
  | 'flank_right'
  // Dynamic state tags (used in mock data and AI responses)
  | string;

export interface PositionTagIndex {
  [key: string]: number;
}

export interface CompositeActionDef {
  semanticAction: VisualActionType;
  targetLogic?: TargetLogic;
  targetRegionId?: string;
  targetUnitId?: string;
  requiredUnitTypes?: string[];
  description?: string;
}

export interface MapDecoration {
  id: string;
  type: "river" | "road" | "label" | "symbol";
  points: [number, number][]; // Line segments or single point for label/symbol
  label?: string; // Text for labels
  style?: "solid" | "dotted" | "dashed" | "wavy";
  color?: string; // Hex or rgba
  width?: number;
}

// How do we define the shape of a region?
export type RegionShapeType = 
  | "point"       // Standard blob (Village, Hill)
  | "path"        // Linear (River, Road, Front Line)
  | "blob"        // Large organic area (Forest, Plain)
  | "noise";      // Scattered (Archipelago, Marsh)

export interface RegionLayoutDef {
  id: string;
  name: string;
  type: RegionShapeType;
  terrain: string;
  // Where is it?
  seeds: number; // How many micro-cells does it consume?
  influence: number; // Radius/Width
  points: [number, number][]; // Guide points (1 for blob, multiple for path)
  isFort?: boolean;
  isCity?: boolean;
}

export interface SemanticPlacement {
  regionId: string;
  tag: PositionTag;
}

export interface SemanticPosition {
  type: AnchorType;
  regionId: string;
  targetId?: string; // For border/sector anchors
  offset?: number; // For border positioning (0-1)
}

export interface Unit {
  id: string
  name: string
  type: "armor" | "infantry" | "cavalry" | "artillery" | "elephant" | "chariot" | "naval"
  owner: "player" | "enemy"
  
  // The calculated "Truth" location (Axial) - populated by Hydrator
  hex?: { q: number, r: number };
  
  // The User/AI intent
  placement?: SemanticPlacement; 
  
  tags: string[]
  visibility?: number
  status?: "fresh" | "engaged" | "wavering" | "routing"
}

export type TargetLogic = 
  | "nearest"        // Default: Head to closest enemy
  | "center_mass"    // Head to average center of enemy
  | "flank_left"     // Target enemy's rightmost unit (their flank)
  | "flank_right"    // Target enemy's leftmost unit
  | "flank"          // Generic flank targeting
  | "rear"           // Target enemy furthest back
  | "specific_region" // Target a specific geographic ID
  | "region"         // Alias for specific_region
  | "specific_unit"  // Target a particular unit ID
  | "self"           // Self-targeting (fortify, hold, retreat)
  | "lowest_health"  // Target weakest enemy
  | "weakest"        // Alias for lowest_health
  | "density"        // Target highest concentration
  | "ally_distress"  // Target ally in danger

export interface CatalystOption {
  id: string
  title: string
  description: string
  semanticAction?: VisualActionType // Made optional for composite-only actions
  targetLogic?: TargetLogic
  targetRegionId?: string
  requiredUnitTypes?: ("armor" | "infantry" | "cavalry" | "artillery" | "elephant" | "chariot" | "naval")[]
  visualEffects?: string[];
  compositeActions?: CompositeActionDef[]; // Main source of action logic
}

export interface MapRegion {
  id: string
  name: string
  points: [number, number][]
  neighbors: string[]; // IDs of adjacent regions
  features?: MapFeature[];
  terrain?: "plains" | "forest" | "mountain" | "urban" | "river" | "swamp" | "mud" | "water" | "ocean"
  isFort?: boolean
  isCity?: boolean
  gridScale?: number // New: Grid density for this region (e.g. 10)
  centroid?: { x: number; y: number } // NEW: For label positioning
  subPolygons?: [number, number][][]; // NEW: If generated by MapPainter (multi-shard regions)
}

export interface MapFeature {
  id: string;
  type: 'river' | 'fort' | 'city' | 'forest';
  location: SemanticPlacement; // Where is this feature located?
}

export type VisualActionType =
  | "ADVANCE"
  | "ASSAULT"
  | "FLANK_LEFT"
  | "FLANK_RIGHT"
  | "RETREAT"
  | "INFILTRATE"
  | "ENCIRCLE"
  | "SPEARHEAD"
  | "FORTIFY"
  | "BLOCKADE"
  | "HOLD"
  | "AMBUSH"
  | "BOMBARD"
  | "SUPPRESS"
  | "SEVER_SUPPLY"
  | "FEINT"
  | "AIRSTRIKE"
  | "RAIN_ARROWS"
  | "TRAMPLE"
  | "NAVAL_RAM"
  | "FIRE_SHIP"
  | "HACK"
  | "EMP_BLAST"
  | "RECON"
  | "COMBINED_ASSAULT"  // Composite: Artillery + Infantry + Cavalry
  | "REGION_BOMBARDMENT" // New: Visual effect on region
  | "REGION_ENCIRCLEMENT" // New: Visual encirclement of region
  // NEW TYPES
  | "HACK"           // Digital attack lines
  | "EMP_BLAST"      // Area of effect disruption
  | "NAVAL_RAM"      // Direct ship collision
  | "FIRE_SHIP"      // Unit becomes a projectile
  | "GATES_OPEN"     // Sabotage action
  | "TRAMPLE"        // Elephant charge
  | "RAIN_ARROWS"    // Massed archery
  // NAVAL ACTIONS
  | "BROADSIDES"     // Massed cannon fire from ship sides
  | "RAKING_FIRE"    // Fire along ship length
  | "BOARDING"       // Close combat boarding action
  | "MANEUVER"      // Tactical ship movement
  | "LINE_OF_BATTLE" // Form a parallel line to enemy formation
  // SPECIAL ACTIONS
  | "DIVERSION"      // Diversionary attack
  | "VICTORY"        // Victory condition
  | "DIPLOMACY";     // Diplomatic action

export interface VisualPlan {
  title: string
  steps: VisualStep[]
}

export interface VisualStep {
  unit_id: string
  action: VisualActionType
  target: string // unit_id or region_id
  pivot?: string // optional intermediate region for pathfinding
  phaseOpacity?: number // for multi-step sequencing (0-1)
}

export interface ActionResolution {
  operation: string
  vectors: Vector[]
  modifiers: {
    river_crossing?: boolean
    urban_combat?: boolean
    enemy_entrenchment?: "low" | "medium" | "high"
    terrain_advantage?: "own" | "enemy" | "neutral"
  }
}

export interface Vector {
  source: string // unit/region ID
  target: string // unit/region ID
  type: string // action type
}

export interface WarRoomScenario {
  id: string // Added scenario ID for switcher
  name: string // Added scenario name
  // NEW: Determines rendering style and generation density
  scaleType?: 'tactical' | 'grand_strategy'; 
  era: "WW2" | "Napoleonic" | "Ancient" | "Medieval"
  playerPolity: string
  enemyPolity: string
  mapRegions: MapRegion[]
  layoutDefs?: RegionLayoutDef[]; // NEW: For Painter's Algorithm generation
  units: Unit[]
  options: CatalystOption[]
  mapDimensions: {
    width: number
    height: number
  }
  narrative_intro?: string
  decorations?: MapDecoration[]; // NEW: Non-gameplay visual layers (rivers, roads, labels)
  hexGrid?: HexData[];
  // Optional lookup map for fast hex->pixel access keyed by "q,r"
  hexIndex?: Record<string, HexData>;
  // NEW: Rivers as border features between regions
  rivers?: {
    id: string;
    pathNodes: string[]; // List of region IDs the river flows BETWEEN or THROUGH
    width: number;
    name: string;
  }[]
}

export interface HexData {
  q: number;
  r: number;
  s: number;
  x: number;
  y: number;
  terrain: 'plains' | 'mud' | 'sand' | 'water' | 'mountain' | 'forest' | 'urban_ruins' | 'factory_floor' | 'swamp';
  structure?: 'fortress' | 'bunker' | 'city_block' | 'airfield' | 'rubble' | 'none';
  infrastructure?: ('road' | 'river' | 'wall')[];
  height?: number;
  regionId: string;
}

export interface AIGameResponse {
  // New Schema Fields (AI SDK will return these)
  thought_chain?: string;
  narrative_outcome?: string;
  unit_updates?: UnitUpdate[];
  visual_fx?: VisualEffect[];
  next_tactical_options?: CatalystOption[];
  
  // Legacy fields (mock data and backwards compat)
  narrative_update?: string;
  state_changes?: StateChange[];
  next_options?: CatalystOption[];
}

// Helper to get the narrative from either field
export function getNarrative(response: AIGameResponse): string {
  return response.narrative_outcome || response.narrative_update || "";
}

// Helper to get state changes from either field  
export function getStateChanges(response: AIGameResponse): StateChange[] {
  // If unit_updates exists, convert to StateChange format
  if (response.unit_updates) {
    return response.unit_updates.map(u => ({
      unit_id: u.unitId,
      action: u.status === 'eliminated' ? 'REMOVE' as const : 
              u.position_update ? 'MOVE' as const : 'UPDATE_STATUS' as const,
      semantic_update: u.position_update,
      new_tags: u.status ? [u.status] : []
    }));
  }
  return response.state_changes || [];
}

// Helper to get next options from either field
export function getNextOptions(response: AIGameResponse): CatalystOption[] {
  return response.next_tactical_options || response.next_options || [];
}

export interface UnitUpdate {
  unitId: string;
  status: "fresh" | "engaged" | "wavering" | "routing" | "eliminated";
  position_update?: SemanticPlacement;
}

// Deprecated but kept for reference - now extends to support all action types in mock data
export interface StateChange {
  unit_id: string
  action: "MOVE" | "UPDATE_STATUS" | "REMOVE" | "HOLD" | "BOMBARD" | "ASSAULT" | "RETREAT" | 
          "FIRE_SHIP" | "NAVAL_RAM" | "ADVANCE" | "FLANK" | "ENCIRCLE" | "SPEARHEAD" | 
          "FORTIFY" | "BOARDING" | "SUPPRESS" | "CHARGING" | "DEFENDING" | "VICTORY" | string
  to_region?: string
  semantic_update?: SemanticPlacement;
  new_tags?: string[]
  new_location?: Location
}

export interface VisualEffect {
  type: "MUD_SPLAT" | "EXPLOSION" | "SMOKE" | "FIRE" | "DUST" | "IMPACT" | "WATER_SPLASH"
  region?: string
  target_unit?: string
  position?: Location
}

export interface GameLoopContext {
  current_round: number
  chosen_tactic: CatalystOption
  scenario: WarRoomScenario
  units: Unit[]
  map_context: {
    weather?: string
    regions: MapRegion[]
  }
}
